const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const products = [
  {
    name: 'Sony WH-1000XM5 Headphones',
    category: 'Headphones',
    brand: 'Sony',
    sku: 'SONY-WH1000XM5',
    description: 'Industry-leading noise canceling headphones with 30-hour battery, multipoint connection, and studio-quality sound. Lightweight design at 250g with ultra-soft ear cushions.',
    price: 34999,
    comparePrice: 39999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'Silver', 'Midnight Blue']),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['1 Year', '2 Years', '3 Years']),
    specs: JSON.stringify({
      'Driver': '30mm',
      'Frequency': '4 Hz–40,000 Hz',
      'Battery': '30 hours (ANC on)',
      'Charge Time': '3.5 hours',
      'Weight': '250g',
      'Connectivity': 'Bluetooth 5.2',
      'Noise Canceling': 'Yes — Industry Leading',
      'Microphone': 'Built-in, call quality AI',
    }),
    stock: 30,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['H-1001', 'H-1002', 'H-1003', 'H-1004', 'H-1005']),
    active: true,
    featured: true,
    weight: '250g',
    tags: JSON.stringify(['headphones', 'noise-canceling', 'sony', 'wireless']),
  },
  {
    name: 'Apple MacBook Pro 14" M5',
    category: 'Laptops',
    brand: 'Apple',
    sku: 'APPLE-MBP14-M5',
    description: 'MacBook Pro with M5 Pro chip, Liquid Retina XDR display, up to 24 hours battery, and the fastest neural engine ever in a Mac. 40% faster than M3. Perfect for AI, video, and professional workflows.',
    price: 219999,
    comparePrice: 249999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1611186871525-b56978cf66cd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1629131726692-1accd0c53ce0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593640408182-31c228f42a89?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Space Black', 'Silver']),
    storageOptions: JSON.stringify(['512GB SSD', '1TB SSD', '2TB SSD']),
    warrantyOptions: JSON.stringify(['1 Year AppleCare', '2 Years AppleCare+', '3 Years AppleCare+']),
    specs: JSON.stringify({
      'Chip': 'Apple M5 Pro',
      'RAM': '24GB Unified',
      'Display': '14.2" Liquid Retina XDR',
      'Resolution': '3024 × 1964',
      'Battery': '24 hours',
      'Ports': '3× Thunderbolt 5, HDMI 2.1, MagSafe 3',
      'Weight': '1.60 kg',
      'OS': 'macOS Sequoia',
    }),
    stock: 15,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['L-2001', 'L-2002', 'L-2003']),
    active: true,
    featured: true,
    weight: '1.60kg',
    tags: JSON.stringify(['laptop', 'macbook', 'apple', 'm5', '2025', 'latest']),
  },
  {
    name: 'ASUS ROG Strix Gaming Laptop',
    category: 'Laptops',
    brand: 'ASUS',
    sku: 'ASUS-ROG-G16',
    description: 'High-performance gaming laptop with RTX 4070 GPU, 240Hz QHD display, per-key RGB keyboard, and advanced cooling with 4-fan system. Dominate every game.',
    price: 169999,
    comparePrice: 189999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Eclipse Gray', 'Volt Green']),
    storageOptions: JSON.stringify(['1TB SSD', '2TB SSD']),
    warrantyOptions: JSON.stringify(['1 Year', '2 Years', '3 Years']),
    specs: JSON.stringify({
      'GPU': 'NVIDIA RTX 4070',
      'CPU': 'Intel i9-13980HX',
      'RAM': '32GB DDR5',
      'Display': '16" QHD 240Hz',
      'Battery': '90Wh',
      'Weight': '2.3 kg',
      'Cooling': '4-Fan Tri-Fan Tech',
      'RGB': 'Per-key Aura Sync',
    }),
    stock: 10,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['G-3001', 'G-3002', 'G-3003']),
    active: true,
    featured: false,
    weight: '2.3kg',
    tags: JSON.stringify(['laptop', 'gaming', 'asus', 'rtx4070']),
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    category: 'Phones',
    brand: 'Samsung',
    sku: 'SAM-S24U',
    description: 'Samsung Galaxy S24 Ultra with built-in S Pen, 200MP camera, titanium frame, and Snapdragon 8 Gen 3. The ultimate Android flagship with AI-powered photography.',
    price: 129999,
    comparePrice: 139999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Titanium Black', 'Titanium Gray', 'Titanium Violet', 'Titanium Yellow']),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB']),
    warrantyOptions: JSON.stringify(['1 Year Samsung', '2 Years Extended', '3 Years Premium']),
    specs: JSON.stringify({
      'Chip': 'Snapdragon 8 Gen 3',
      'RAM': '12GB',
      'Camera': '200MP + 12MP + 10MP + 50MP',
      'Display': '6.8" Dynamic AMOLED 120Hz',
      'Battery': '5000mAh',
      'S Pen': 'Built-in',
      'Build': 'Titanium Frame + Gorilla Glass Armor',
      'OS': 'Android 14 + One UI 6.1',
    }),
    stock: 22,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['P-4001', 'P-4002', 'P-4003']),
    active: true,
    featured: true,
    weight: '232g',
    tags: JSON.stringify(['phone', 'samsung', 'android', 's-pen']),
  },
  {
    name: 'iPhone 15 Pro Max',
    category: 'Phones',
    brand: 'Apple',
    sku: 'APPLE-IP15PM',
    description: 'Apple iPhone 15 Pro Max with titanium design, A17 Pro chip, 48MP main camera with 5× telephoto zoom, USB-C, and Action Button. The most powerful iPhone ever made.',
    price: 119999,
    comparePrice: null,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1581016716282-6f6e04f6a1f2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574755393849-623942496936?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black Titanium', 'White Titanium', 'Blue Titanium', 'Natural Titanium']),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB']),
    warrantyOptions: JSON.stringify(['1 Year AppleCare', '2 Years AppleCare+', '3 Years AppleCare+']),
    specs: JSON.stringify({
      'Chip': 'Apple A17 Pro',
      'RAM': '8GB',
      'Camera': '48MP Main + 12MP Ultra + 12MP 5× Tele',
      'Display': '6.7" Super Retina XDR ProMotion',
      'Battery': 'Up to 29 hours video',
      'Build': 'Grade 5 Titanium + Ceramic Shield',
      'Charging': 'USB-C (USB 3), MagSafe',
      'OS': 'iOS 17',
    }),
    stock: 18,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['P-5001', 'P-5002', 'P-5003']),
    active: true,
    featured: true,
    weight: '221g',
    tags: JSON.stringify(['phone', 'iphone', 'apple', 'titanium']),
  },
  {
    name: 'Apple Watch Ultra 2',
    category: 'Wearables',
    brand: 'Apple',
    sku: 'APPLE-AWU2',
    description: 'The most rugged and capable Apple Watch. 49mm titanium case, dual-frequency GPS, 36-hour battery in standard mode, and rated to EN13319 for diving to 100m.',
    price: 79999,
    comparePrice: null,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1523475496153-3b2b7cd1b5e2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Natural Titanium', 'Black Titanium']),
    storageOptions: JSON.stringify(['Standard (64GB)']),
    warrantyOptions: JSON.stringify(['1 Year AppleCare', '2 Years AppleCare+']),
    specs: JSON.stringify({
      'Case': '49mm Titanium',
      'Chip': 'Apple S9',
      'Display': 'Always-On Retina LTPO',
      'Battery': '36 hours (low-power: 60 hours)',
      'Water Resistance': '100m EN13319',
      'GPS': 'L1 + L5 dual-frequency',
      'Connectivity': 'Bluetooth 5.3, Wi-Fi, LTE',
      'Sensors': 'Blood O2, ECG, Temp, Crash Detection',
    }),
    stock: 12,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['W-6001', 'W-6002', 'W-6003']),
    active: true,
    featured: true,
    weight: '61.4g',
    tags: JSON.stringify(['smartwatch', 'apple', 'wearable', 'ultra', 'rugged']),
  },
  {
    name: 'Garmin Fenix 7X Solar',
    category: 'Wearables',
    brand: 'Garmin',
    sku: 'GARMIN-FX7X',
    description: 'Premium multisport GPS smartwatch with solar charging lens, 37-day battery life, built-in maps, and health monitoring. Built for athletes who refuse to stop.',
    price: 59999,
    comparePrice: 69999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1617043786394-f977fa12eddf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Carbon Gray DLC', 'Mineral Blue DLC', 'Titanium/Whitestone']),
    storageOptions: JSON.stringify(['Standard (32GB)']),
    warrantyOptions: JSON.stringify(['1 Year Garmin', '2 Years Extended']),
    specs: JSON.stringify({
      'Battery': '37 days (solar), 28 days (GPS)',
      'Display': '1.4" Sapphire MIP',
      'Build': 'Fiber-reinforced polymer + Titanium',
      'Water Rating': '10 ATM (100m)',
      'GPS': 'Multi-band GPS, GLONASS, Galileo',
      'Storage': '32GB music + maps',
      'Health': 'HRV, SpO2, Stress, Sleep',
      'Weight': '89g',
    }),
    stock: 8,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['W-7001', 'W-7002']),
    active: true,
    featured: false,
    weight: '89g',
    tags: JSON.stringify(['smartwatch', 'garmin', 'multisport', 'solar', 'gps']),
  },
  {
    name: 'Sony 65" BRAVIA XR A95L OLED TV',
    category: 'TVs',
    brand: 'Sony',
    sku: 'SONY-A95L-65',
    description: 'QD-OLED panel with Cognitive Processor XR, delivering 4K 120fps, XR Triluminos Max, and Acoustic Surface Audio+. The best TV for PS5 and home cinema.',
    price: 299999,
    comparePrice: 349999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1601944179066-29786cb9d32a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1571415060716-baff5f717c37?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black']),
    storageOptions: JSON.stringify(['65 inch', '55 inch', '77 inch']),
    warrantyOptions: JSON.stringify(['1 Year Sony', '3 Years Extended', '5 Years Premium']),
    specs: JSON.stringify({
      'Panel': 'QD-OLED',
      'Resolution': '4K (3840×2160)',
      'Refresh Rate': '120Hz (4K)',
      'Processor': 'Cognitive Processor XR',
      'HDR': 'Dolby Vision, HDR10, HLG',
      'Audio': 'Acoustic Surface Audio+ 60W',
      'Smart TV': 'Google TV + Chromecast',
      'Gaming': 'HDMI 2.1, VRR, ALLM, 120fps 4K',
    }),
    stock: 6,
    lowStockThreshold: 2,
    serialNumbers: JSON.stringify(['T-8001', 'T-8002']),
    active: true,
    featured: false,
    weight: '28.3kg',
    tags: JSON.stringify(['tv', 'oled', 'sony', '4k', 'gaming']),
  },
  {
    name: 'iPad Pro 13" M4',
    category: 'Tablets',
    brand: 'Apple',
    sku: 'APPLE-IPADPRO13M4',
    description: 'Impossibly thin at 5.1mm, Apple iPad Pro M4 with Ultra Retina XDR OLED tandem display, landscape 12MP camera, and the most powerful chip ever in an iPad.',
    price: 109999,
    comparePrice: null,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1642790551116-18a150d248ed?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Space Black', 'Silver']),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB', '2TB']),
    warrantyOptions: JSON.stringify(['1 Year AppleCare', '2 Years AppleCare+']),
    specs: JSON.stringify({
      'Chip': 'Apple M4',
      'Display': '13" Ultra Retina XDR OLED Tandem',
      'Brightness': '1000 nits (peak 1600 nits)',
      'Thickness': '5.1mm',
      'Camera': '12MP landscape wide + 12MP TrueDepth',
      'Connectivity': 'Thunderbolt 4 / USB4',
      'Biometrics': 'Face ID',
      'Weight': '579g (Wi-Fi)',
    }),
    stock: 14,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['TAB-9001', 'TAB-9002', 'TAB-9003']),
    active: true,
    featured: true,
    weight: '579g',
    tags: JSON.stringify(['tablet', 'ipad', 'apple', 'm4']),
  },
  {
    name: 'Samsung Galaxy Buds3 Pro',
    category: 'Audio',
    brand: 'Samsung',
    sku: 'SAM-BUDS3PRO',
    description: 'Galaxy Buds3 Pro with Intelligent ANC, 360° Audio, Hi-Fi sound with 24-bit audio resolution, and up to 30 hours total playtime with the case.',
    price: 22999,
    comparePrice: 27999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1606220838315-056192d5e927?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1625481645697-d0e24e85de59?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Silver', 'White']),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['1 Year Samsung', '2 Years Extended']),
    specs: JSON.stringify({
      'Driver': '10.5mm woofer + 6.1mm tweeter',
      'ANC': 'Intelligent ANC (up to -29dB)',
      'Battery': '6h buds + 24h case',
      'Audio': '24-bit Hi-Fi, 360 Audio',
      'Connectivity': 'Bluetooth 5.4',
      'Water': 'IPX7 buds, IPX2 case',
      'Features': 'Head tracking, Auto switch',
      'Weight': '5.9g per bud',
    }),
    stock: 35,
    lowStockThreshold: 8,
    serialNumbers: JSON.stringify(['E-10001', 'E-10002', 'E-10003']),
    active: true,
    featured: false,
    weight: '5.9g (per bud)',
    tags: JSON.stringify(['earbuds', 'samsung', 'wireless', 'anc']),
  },
  {
    name: 'DJI Osmo Pocket 3',
    category: 'Cameras',
    brand: 'DJI',
    sku: 'DJI-OSMO3',
    description: 'Pocket gimbal camera with 1-inch CMOS sensor, 4K/120fps video, ActiveTrack 6.0 subject tracking, and 140-minute battery. The perfect travel camera.',
    price: 49999,
    comparePrice: 59999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1533425962554-8c34d027f9d4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1557825835-70d97c4aa567?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Glacier Blue', 'Midnight Black']),
    storageOptions: JSON.stringify(['Standard (Standalone)', 'Creator Combo']),
    warrantyOptions: JSON.stringify(['1 Year DJI', '2 Years DJI Care Refresh']),
    specs: JSON.stringify({
      'Sensor': '1-inch CMOS',
      'Video': '4K/120fps, 2.7K/120fps, 1080p/240fps',
      'Stabilization': '3-axis gimbal + EIS',
      'Tracking': 'ActiveTrack 6.0',
      'Battery': '140 minutes',
      'Display': '2" OLED Touchscreen',
      'Weight': '179g (with handle)',
      'Storage': 'microSD up to 2TB',
    }),
    stock: 9,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['C-11001', 'C-11002']),
    active: true,
    featured: false,
    weight: '179g',
    tags: JSON.stringify(['camera', 'dji', 'gimbal', 'vlog', '4k']),
  },
  {
    name: 'Anker 737 PowerBank 24,000mAh',
    category: 'Accessories',
    subcategory: 'Power Banks',
    brand: 'Anker',
    sku: 'ANKER-737',
    description: 'Massive 24,000mAh power bank with 140W max output, dual USB-C and USB-A ports, smart display showing watts and battery %, and fast charge for laptops.',
    price: 12999,
    comparePrice: 15999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560732488-6b0df240254a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'Blue']),
    colorStock: JSON.stringify({ Black: 25, Blue: 15 }),
    storageOptions: JSON.stringify(['24,000mAh']),
    warrantyOptions: JSON.stringify(['18 Months Anker', '3 Years Extended']),
    specs: JSON.stringify({
      'Capacity': '24,000mAh / 87.7Wh',
      'Max Output': '140W (USB-C1)',
      'Ports': '2× USB-C, 1× USB-A',
      'Display': 'LED watt/battery display',
      'Input': '140W max USB-C',
      'Passthrough': 'Yes',
      'Weight': '661g',
      'Dimensions': '163.5 × 58.5 × 40.2mm',
    }),
    stock: 40,
    lowStockThreshold: 10,
    serialNumbers: JSON.stringify(['A-12001', 'A-12002', 'A-12003']),
    active: true,
    featured: false,
    weight: '661g',
    tags: JSON.stringify(['powerbank', 'anker', 'charging', 'accessory']),
  },

  // ===== TVs =====
  {
    name: 'Samsung 65" QLED 4K Smart TV',
    category: 'TVs',
    subcategory: 'Smart TVs',
    brand: 'Samsung',
    sku: 'SAM-QN65Q80C',
    description: 'Samsung QLED 4K Smart TV with Quantum Dot color, Neo Quantum Processor 4K, and Object Tracking Sound. 144Hz refresh rate perfect for gaming. Built-in Tizen OS with Netflix, YouTube, Prime Video.',
    price: 149999,
    comparePrice: 179999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1571415060716-baff5f717c37?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1461151304267-38535e780c79?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Titan Gray']),
    colorStock: JSON.stringify({ 'Titan Gray': 10 }),
    storageOptions: JSON.stringify(['55"', '65"', '75"', '85"']),
    storageStock: JSON.stringify({ '55"': 5, '65"': 8, '75"': 4, '85"': 2 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year Samsung Care']),
    specs: JSON.stringify({
      'Panel': 'QLED (Quantum Dot)',
      'Resolution': '3840 × 2160 (4K)',
      'Refresh Rate': '144Hz',
      'HDR': 'Quantum HDR 20x',
      'Audio': '60W Object Tracking Sound',
      'Smart OS': 'Tizen 7.0',
      'Ports': '4× HDMI 2.1, 2× USB, LAN',
      'Gaming': 'Gaming Hub, Auto Low Latency',
    }),
    stock: 19,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['TV-1001', 'TV-1002', 'TV-1003']),
    active: true,
    featured: true,
    weight: '28.5kg',
    tags: JSON.stringify(['tv', 'samsung', '4k', 'qled', 'smart-tv']),
  },
  {
    name: 'LG C3 55" OLED evo Smart TV',
    category: 'TVs',
    subcategory: 'OLED TVs',
    brand: 'LG',
    sku: 'LG-C3-55',
    description: 'LG C3 OLED evo with self-lit pixels for perfect blacks, α9 AI Processor Gen6, Dolby Vision IQ, Dolby Atmos, NVIDIA G-Sync, and FreeSync Premium Pro. The ultimate TV for movies and gaming.',
    price: 139999,
    comparePrice: 169999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1593359677879-a4bb92f4834c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1601944177325-f8867652837f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1552975084-6e027cd345c2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black']),
    colorStock: JSON.stringify({ Black: 7 }),
    storageOptions: JSON.stringify(['48"', '55"', '65"', '77"']),
    storageStock: JSON.stringify({ '48"': 3, '55"': 4, '65"': 2, '77"': 1 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year LG Care+']),
    specs: JSON.stringify({
      'Panel': 'OLED evo (self-lit)',
      'Resolution': '3840 × 2160 (4K)',
      'Refresh Rate': '120Hz',
      'HDR': 'Dolby Vision IQ, HDR10, HLG',
      'Audio': '60W 4.2ch, Dolby Atmos',
      'Smart OS': 'webOS 23',
      'Gaming': 'G-Sync, FreeSync, 0.1ms response',
      'Ports': '4× HDMI 2.1, 3× USB',
    }),
    stock: 10,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['TV-2001', 'TV-2002']),
    active: true,
    featured: true,
    weight: '18.4kg',
    tags: JSON.stringify(['tv', 'lg', 'oled', '4k', 'dolby', 'gaming-tv']),
  },
  {
    name: 'TCL 43" 4K Smart Android TV',
    category: 'TVs',
    subcategory: '4K TVs',
    brand: 'TCL',
    sku: 'TCL-43P735',
    description: 'TCL 4K Smart Android TV with built-in Chromecast, Google Assistant, Dolby Audio, and HDR10+. Ideal for apartments and bedrooms. Excellent value for money.',
    price: 44999,
    comparePrice: 54999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1542393545-10f5cde2c810?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1494173853739-c21f58b16055?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Brushed Metal Black']),
    colorStock: JSON.stringify({ 'Brushed Metal Black': 20 }),
    storageOptions: JSON.stringify(['32"', '43"', '50"', '55"']),
    storageStock: JSON.stringify({ '32"': 10, '43"': 8, '50"': 7, '55"': 5 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year TCL']),
    specs: JSON.stringify({
      'Panel': 'LED-backlit',
      'Resolution': '3840 × 2160 (4K)',
      'Refresh Rate': '60Hz',
      'HDR': 'HDR10+, Dolby Vision',
      'Audio': '20W Dolby Audio',
      'Smart OS': 'Android TV 11',
      'Voice': 'Google Assistant + Alexa',
      'Ports': '3× HDMI, 2× USB, AV',
    }),
    stock: 30,
    lowStockThreshold: 8,
    serialNumbers: JSON.stringify(['TV-3001', 'TV-3002', 'TV-3003', 'TV-3004']),
    active: true,
    featured: false,
    weight: '8.1kg',
    tags: JSON.stringify(['tv', 'tcl', '4k', 'android', 'budget-tv', 'smart-tv']),
  },

  // ===== Others Category =====
  {
    name: 'Baseus 100W GaN Charger (4-Port)',
    category: 'Others',
    subcategory: 'Chargers',
    brand: 'Baseus',
    sku: 'BAS-GAN100W4P',
    description: 'Baseus 100W GaN III desktop charger with 4 ports (2× USB-C + 2× USB-A). Charge your laptop, phone, tablet, and earbuds simultaneously. GaN III technology runs 40% cooler than standard chargers.',
    price: 5999,
    comparePrice: 7999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1601524909162-ae8725290836?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White', 'Black']),
    colorStock: JSON.stringify({ White: 20, Black: 25 }),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year']),
    specs: JSON.stringify({
      'Max Output': '100W total (single port: 65W)',
      'Ports': '2× USB-C PD, 2× USB-A QC4+',
      'Technology': 'GaN III',
      'Foldable Plug': 'Yes',
      'Safety': 'OVP, OCP, OTP, Short-circuit',
      'Dimensions': '75 × 75 × 30mm',
      'Weight': '185g',
      'Compatibility': 'MacBook, iPad, iPhone, Android',
    }),
    stock: 45,
    lowStockThreshold: 10,
    serialNumbers: JSON.stringify(['CH-1001', 'CH-1002']),
    active: true,
    featured: false,
    weight: '185g',
    tags: JSON.stringify(['charger', 'gan', 'baseus', 'usb-c', 'fast-charge']),
  },
  {
    name: 'Hollyland Lark M2 Wireless Microphone',
    category: 'Others',
    subcategory: 'Wireless Microphones',
    brand: 'Hollyland',
    sku: 'HOLLY-LARKM2',
    description: 'Ultra-compact wireless microphone system for smartphones, DSLR, and mirrorless cameras. 300m range, 48kHz/24-bit audio, built-in noise cancellation, 8-hour battery. Perfect for vloggers and journalists.',
    price: 14999,
    comparePrice: 18999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516280030429-27b98b522169?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'White']),
    colorStock: JSON.stringify({ Black: 12, White: 8 }),
    storageOptions: JSON.stringify(['1 TX + 1 RX', '2 TX + 1 RX']),
    storageStock: JSON.stringify({ '1 TX + 1 RX': 10, '2 TX + 1 RX': 10 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year Hollyland']),
    specs: JSON.stringify({
      'Range': 'Up to 300m (line of sight)',
      'Audio': '48kHz / 24-bit',
      'Frequency': '2.4GHz (auto freq hopping)',
      'Noise Cancellation': 'AI noise reduction',
      'Battery TX': '8 hours',
      'Charging': 'USB-C case (additional 8h)',
      'Latency': '20ms',
      'Compatibility': 'iOS, Android, DSLR, PC',
    }),
    stock: 20,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['MIC-1001', 'MIC-1002']),
    active: true,
    featured: false,
    weight: '35g (TX)',
    tags: JSON.stringify(['microphone', 'wireless', 'vlog', 'hollyland', 'content-creator']),
  },
  {
    name: 'Flexible Selfie Stick Tripod',
    category: 'Others',
    subcategory: 'Selfie Sticks',
    brand: 'KigaliTech',
    sku: 'KT-SELFIE-TRI',
    description: 'All-in-one selfie stick and flexible tripod with Bluetooth remote. Extends to 70cm, wraps around poles, bends into any shape. Works with iPhone and Android. Great for travel photos and live streaming.',
    price: 2999,
    comparePrice: 4499,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'Rose Gold', 'Silver']),
    colorStock: JSON.stringify({ Black: 20, 'Rose Gold': 10, Silver: 15 }),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months']),
    specs: JSON.stringify({
      'Extended Length': '70cm',
      'Folded Length': '21cm',
      'Max Load': '500g',
      'Remote': 'Bluetooth 5.0 (10m range)',
      'Tripod': 'Flexible octopus legs',
      'Mount': 'Universal phone clip (5.5–9cm)',
      'Battery': 'Included (CR2032)',
      'Weight': '230g',
    }),
    stock: 45,
    lowStockThreshold: 10,
    serialNumbers: JSON.stringify(['SEL-1001', 'SEL-1002']),
    active: true,
    featured: false,
    weight: '230g',
    tags: JSON.stringify(['selfie', 'tripod', 'bluetooth', 'photography', 'accessory']),
  },
  {
    name: 'Romoss Sense 8P+ 30,000mAh PowerBank',
    category: 'Others',
    subcategory: 'Power Banks',
    brand: 'Romoss',
    sku: 'ROMOSS-S8P',
    description: 'Romoss 30,000mAh ultra-high-capacity power bank with 22.5W fast charge, dual USB-C and dual USB-A ports, LCD display. Can charge a phone up to 7 times. Great for travel and load-shedding.',
    price: 8999,
    comparePrice: 10999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'White']),
    colorStock: JSON.stringify({ Black: 30, White: 20 }),
    storageOptions: JSON.stringify(['20,000mAh', '30,000mAh']),
    storageStock: JSON.stringify({ '20,000mAh': 20, '30,000mAh': 30 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year Romoss']),
    specs: JSON.stringify({
      'Capacity': '30,000mAh / 111Wh',
      'Max Output': '22.5W (USB-A QC)',
      'USB-C Output': '18W PD',
      'Ports': '2× USB-A, 2× USB-C, 1× Micro',
      'Display': 'LED percentage display',
      'Phone Charges': '~7× typical smartphone',
      'Weight': '582g',
      'Airline Safe': 'Yes (under 100Wh limit not applicable)',
    }),
    stock: 50,
    lowStockThreshold: 12,
    serialNumbers: JSON.stringify(['PB-2001', 'PB-2002', 'PB-2003']),
    active: true,
    featured: false,
    weight: '582g',
    tags: JSON.stringify(['powerbank', 'romoss', 'charging', 'travel', 'loadshedding']),
  },
  {
    name: 'USB-C Hub 10-in-1',
    category: 'Others',
    subcategory: 'Accessories',
    brand: 'Ugreen',
    sku: 'UGREEN-HUB10',
    description: 'Ugreen 10-in-1 USB-C hub with 4K HDMI, 100W PD, SD/TF card reader, 3× USB 3.0, USB-C data port, Ethernet, and audio jack. Works with MacBook, iPad Pro, and all USB-C laptops.',
    price: 7499,
    comparePrice: 9999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593640408182-31c228f42a89?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Space Gray', 'Silver']),
    colorStock: JSON.stringify({ 'Space Gray': 18, Silver: 12 }),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year Ugreen']),
    specs: JSON.stringify({
      'Ports': '3× USB-A 3.0, 1× USB-C data, HDMI, 100W PD, SD, TF, LAN, Audio',
      'HDMI': '4K/60Hz',
      'PD Charging': '100W passthrough',
      'USB-A Speed': 'Up to 5Gbps',
      'Ethernet': '1000Mbps (Gigabit)',
      'Card Reader': 'SD + TF (MicroSD) simultaneous',
      'Cable Length': '20cm',
      'Compatibility': 'MacBook Pro/Air, iPad Pro, Windows',
    }),
    stock: 30,
    lowStockThreshold: 8,
    serialNumbers: JSON.stringify(['HUB-1001', 'HUB-1002']),
    active: true,
    featured: false,
    weight: '110g',
    tags: JSON.stringify(['hub', 'usb-c', 'ugreen', 'macbook', 'dongle']),
  },
  {
    name: 'Ring Light 18" with Tripod & Phone Holder',
    category: 'Others',
    subcategory: 'Content Creator',
    brand: 'Neewer',
    sku: 'NEEWER-RL18',
    description: '18-inch LED ring light kit for TikTok, YouTube, Instagram, and video calls. 3 color temperatures, 11 brightness levels, 70" adjustable stand, phone holder + ball head for cameras. Plug & play.',
    price: 6999,
    comparePrice: 8999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1614680376408-16afefa3332b?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1525629545813-45fc6f679fc8?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White/Silver']),
    colorStock: JSON.stringify({ 'White/Silver': 25 }),
    storageOptions: JSON.stringify(['18" Kit', '12" Kit']),
    storageStock: JSON.stringify({ '18" Kit': 15, '12" Kit': 10 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months']),
    specs: JSON.stringify({
      'Diameter': '18 inches (46cm)',
      'LED Power': '65W',
      'Color Temp': '3200K, 4500K, 5500K',
      'Brightness': '11 levels (0–100%)',
      'Stand Height': '70" (178cm) max',
      'Phone Mount': 'Universal (rotatable 360°)',
      'Power': 'AC plug (USB dimmer)',
      'Bag': 'Carrying bag included',
    }),
    stock: 25,
    lowStockThreshold: 6,
    serialNumbers: JSON.stringify(['RL-1001', 'RL-1002']),
    active: true,
    featured: false,
    weight: '2.1kg (full kit)',
    tags: JSON.stringify(['ring-light', 'neewer', 'creator', 'tiktok', 'youtube', 'streaming']),
  },

  // ===== Cameras =====
  {
    name: 'iPhone 17 Pro Max',
    category: 'Phones',
    brand: 'Apple',
    sku: 'APPLE-IP17PM',
    description: 'Apple iPhone 17 Pro Max with A19 Pro chip, all-new 48MP periscope telephoto at 5× zoom, 4K120 ProRes video with Camera Control, and ultra-thin titanium design. The most capable iPhone ever made.',
    price: 139999,
    comparePrice: null,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1574755393849-623942496936?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1591337676887-a217a6970a8a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Desert Titanium', 'Black Titanium', 'White Titanium', 'Natural Titanium']),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB']),
    warrantyOptions: JSON.stringify(['1 Year AppleCare', '2 Years AppleCare+', '3 Years AppleCare+']),
    specs: JSON.stringify({
      'Chip': 'Apple A19 Pro',
      'Camera': '48MP Fusion + 48MP Ultra Wide + 48MP 5× Periscope Tele',
      'Video': '4K120fps ProRes, Camera Control button, spatial audio',
      'Display': '6.9" Super Retina XDR ProMotion (120Hz)',
      'Battery': 'Up to 36 hours video playback',
      'Build': 'Grade 5 Titanium + Ceramic Shield Gen 2',
      'Charging': 'USB-C 3, MagSafe 30W',
      'OS': 'iOS 18 with Apple Intelligence',
    }),
    stock: 20,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['P-17001', 'P-17002', 'P-17003']),
    active: true,
    featured: true,
    weight: '227g',
    genuine: true,
    tags: JSON.stringify(['phone', 'iphone', 'apple', 'a19pro', '2025', 'latest']),
  },
  {
    name: 'Samsung Galaxy S26 Ultra',
    category: 'Phones',
    brand: 'Samsung',
    sku: 'SAM-S26U',
    description: 'Samsung Galaxy S26 Ultra with Snapdragon 8 Elite Gen 2, Galaxy AI Pro, 200MP ProVisual Engine camera, built-in S Pen, and aerospace-grade titanium frame. The ultimate 2026 Android flagship.',
    price: 149999,
    comparePrice: null,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Titanium Midnight', 'Titanium Silver', 'Titanium Jade', 'Titanium Sanddune']),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB']),
    warrantyOptions: JSON.stringify(['1 Year Samsung', '2 Years Extended', '3 Years Premium']),
    specs: JSON.stringify({
      'Chip': 'Snapdragon 8 Elite Gen 2 for Galaxy',
      'RAM': '12GB',
      'Camera': '200MP ProVisual + 50MP 5× + 10MP 3× + 12MP UW',
      'Display': '6.9" Dynamic AMOLED 2X 120Hz QHD+',
      'Battery': '5100mAh (65W fast + 15W wireless)',
      'S Pen': 'Built-in, 0.7mm tip',
      'AI': 'Galaxy AI Pro — on-device LLM, Live Translate, Circle to Search',
      'OS': 'Android 16 + One UI 8',
    }),
    stock: 18,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['P-26001', 'P-26002', 'P-26003']),
    active: true,
    featured: true,
    weight: '215g',
    genuine: true,
    tags: JSON.stringify(['phone', 'samsung', 's26', 'ultra', '2026', 'latest', 'galaxy-ai']),
  },
  {
    name: 'Samsung Galaxy Z Fold 7',
    category: 'Phones',
    brand: 'Samsung',
    sku: 'SAM-ZF7',
    description: 'Samsung Galaxy Z Fold 7 with Snapdragon 8 Elite Gen 2, 7.6" foldable Dynamic AMOLED 2X display, Galaxy AI Pro, and ultra-thin Armor Aluminum hinge. The future of smartphones in your pocket.',
    price: 179999,
    comparePrice: 199999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Crafted Black', 'Silver Shadow', 'Navy']),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB']),
    warrantyOptions: JSON.stringify(['1 Year Samsung', '2 Years Extended', '3 Years Premium']),
    specs: JSON.stringify({
      'Chip': 'Snapdragon 8 Elite Gen 2 for Galaxy',
      'RAM': '12GB',
      'Inner Display': '7.6" Dynamic AMOLED 2X 120Hz',
      'Cover Display': '6.3" Dynamic AMOLED 2X 120Hz',
      'Camera': '200MP Main + 12MP UW + 10MP 3× Tele',
      'Battery': '4500mAh (45W + 15W wireless)',
      'Build': 'Armor Aluminum 2 + IPX8',
      'OS': 'Android 16 + One UI 8 Foldable',
    }),
    stock: 10,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['F-7001', 'F-7002', 'F-7003']),
    active: true,
    featured: true,
    weight: '236g',
    genuine: true,
    tags: JSON.stringify(['phone', 'samsung', 'fold', 'foldable', '2026', 'latest']),
  },
  {
    name: 'GoPro HERO12 Black',
    category: 'Cameras',
    subcategory: 'Action Cameras',
    brand: 'GoPro',
    sku: 'GOPRO-HERO12',
    description: 'GoPro HERO12 Black with HyperSmooth 6.0 stabilization, 5.3K60 video, 27MP photos, 360° Horizon Lock, and Enduro battery for 70% longer cold-weather battery. Waterproof to 10m.',
    price: 39999,
    comparePrice: 44999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1533425962554-8c34d027f9d4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586158291800-2665f07bba79?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1557825835-70d97c4aa567?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black']),
    colorStock: JSON.stringify({ Black: 20 }),
    storageOptions: JSON.stringify(['Standard', 'Creator Edition']),
    storageStock: JSON.stringify({ Standard: 15, 'Creator Edition': 5 }),
    warrantyOptions: JSON.stringify(['1 Year GoPro', '2 Years GoPro Plus']),
    specs: JSON.stringify({
      'Video': '5.3K60 / 4K120 / 2.7K240',
      'Photo': '27MP + RAW',
      'Stabilization': 'HyperSmooth 6.0 + 360° Horizon Lock',
      'Waterproof': '10m without housing',
      'Battery': 'Enduro rechargeable (improved cold weather)',
      'Display': '2.27" rear + 1.4" front',
      'Audio': '3 microphones wind noise reduction',
      'Connectivity': 'Bluetooth 5.0, Wi-Fi, USB-C',
    }),
    stock: 20,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['GP-1001', 'GP-1002', 'GP-1003']),
    active: true,
    featured: true,
    weight: '154g',
    genuine: true,
    tags: JSON.stringify(['camera', 'gopro', 'action-cam', '4k', 'waterproof']),
  },
  {
    name: 'Insta360 X4',
    category: 'Cameras',
    subcategory: 'Action Cameras',
    brand: 'Insta360',
    sku: 'INSTA360-X4',
    description: 'Insta360 X4 360° camera with 8K30 resolution, AI Invisible Selfie Stick, FlowState stabilization, and me-Mode. Capture everything and reframe shots later. 135-minute battery life.',
    price: 49999,
    comparePrice: 59999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1533425962554-8c34d027f9d4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586158291800-2665f07bba79?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black']),
    colorStock: JSON.stringify({ Black: 12 }),
    storageOptions: JSON.stringify(['Standard', 'Adventure Bundle']),
    storageStock: JSON.stringify({ Standard: 10, 'Adventure Bundle': 2 }),
    warrantyOptions: JSON.stringify(['1 Year Insta360', '2 Years Extended']),
    specs: JSON.stringify({
      'Video': '8K30 / 5.7K60 / 4K120 360°',
      'Photo': '72MP 360°',
      'Stabilization': 'FlowState + Horizon Lock',
      'Waterproof': '10m without housing',
      'Battery': '2290mAh (135 min)',
      'Invisible Stick': 'AI-powered removal',
      'App': 'Insta360 AI editing',
      'Weight': '203g',
    }),
    stock: 12,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['I360-1001', 'I360-1002']),
    active: true,
    featured: true,
    weight: '203g',
    genuine: true,
    tags: JSON.stringify(['camera', 'insta360', '360-video', '8k', 'action-cam']),
  },
  {
    name: 'Sony ZV-E10 II Mirrorless Vlog Camera',
    category: 'Cameras',
    subcategory: 'Mirrorless Cameras',
    brand: 'Sony',
    sku: 'SONY-ZVE10II',
    description: 'Sony ZV-E10 II APS-C mirrorless camera built for content creators. 26MP sensor, 4K60p video with phase-detect AF, front-flip screen, built-in ND filter, and product showcase mode.',
    price: 89999,
    comparePrice: 99999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'White']),
    colorStock: JSON.stringify({ Black: 8, White: 4 }),
    storageOptions: JSON.stringify(['Body Only', 'Kit with 16-50mm']),
    storageStock: JSON.stringify({ 'Body Only': 8, 'Kit with 16-50mm': 4 }),
    warrantyOptions: JSON.stringify(['1 Year Sony', '2 Years Sony Extended']),
    specs: JSON.stringify({
      'Sensor': '26MP APS-C Exmor R CMOS',
      'Video': '4K60p (Super 35), 1080p120',
      'AF': 'Phase-Detect + AI Subject Recognition',
      'Stabilization': 'Electronic + in-lens',
      'Display': 'Front-flip 3" touchscreen',
      'Built-in ND': '3-stop variable ND',
      'Audio': '3-capsule mic + directional',
      'Connectivity': 'USB-C, Bluetooth, Wi-Fi',
    }),
    stock: 12,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['SONY-CAM-1001', 'SONY-CAM-1002']),
    active: true,
    featured: false,
    weight: '291g',
    genuine: true,
    tags: JSON.stringify(['camera', 'sony', 'mirrorless', 'vlog', '4k', 'aps-c']),
  },

  // ===== More Tablets =====
  {
    name: 'Samsung Galaxy Tab S9 Ultra',
    category: 'Tablets',
    subcategory: 'Android Tablets',
    brand: 'Samsung',
    sku: 'SAM-TABS9U',
    description: 'Samsung Galaxy Tab S9 Ultra with massive 14.6" Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, 12,000mAh battery, S Pen included, and IP68 water resistance. The Android tablet for professionals.',
    price: 119999,
    comparePrice: 139999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1627200401584-05dbeaee49e8?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Graphite', 'Beige', 'Lime']),
    colorStock: JSON.stringify({ Graphite: 8, Beige: 4, Lime: 3 }),
    storageOptions: JSON.stringify(['256GB', '512GB', '1TB']),
    storageStock: JSON.stringify({ '256GB': 8, '512GB': 5, '1TB': 2 }),
    warrantyOptions: JSON.stringify(['1 Year Samsung', '2 Years Extended', '3 Years Premium']),
    specs: JSON.stringify({
      'Chip': 'Snapdragon 8 Gen 2 for Galaxy',
      'RAM': '12GB / 16GB',
      'Display': '14.6" Dynamic AMOLED 2X 120Hz',
      'Camera': '13MP + 8MP rear, 12MP + 12UW front',
      'Battery': '12,000mAh (45W fast charge)',
      'S Pen': 'Included',
      'Water Rating': 'IP68',
      'OS': 'Android 13 + One UI 5.1',
    }),
    stock: 15,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['TAB-S9-1001', 'TAB-S9-1002']),
    active: true,
    featured: true,
    weight: '732g',
    genuine: true,
    tags: JSON.stringify(['tablet', 'samsung', 'android', 's-pen', 'amoled']),
  },

  // ===== Routers =====
  {
    name: 'TP-Link Deco XE75 Wi-Fi 6E Mesh',
    category: 'Routers',
    subcategory: 'Mesh Routers',
    brand: 'TP-Link',
    sku: 'TPLINK-DECOXE75',
    description: 'TP-Link Deco XE75 Wi-Fi 6E tri-band mesh router system. Cover up to 5,500 sq ft with 6GHz backhaul, 3.6 Gbps speeds, 2× 2.5G ports, and parental controls. Works with Alexa.',
    price: 34999,
    comparePrice: 42999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524139094135-77b60a43dc2a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1606229365485-93a3b8ee0385?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593640408182-31c228f42a89?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White']),
    colorStock: JSON.stringify({ White: 20 }),
    storageOptions: JSON.stringify(['1-Pack', '2-Pack', '3-Pack']),
    storageStock: JSON.stringify({ '1-Pack': 10, '2-Pack': 8, '3-Pack': 4 }),
    warrantyOptions: JSON.stringify(['3 Months', '6 Months', '1 Year TP-Link']),
    specs: JSON.stringify({
      'Wi-Fi Standard': 'Wi-Fi 6E (802.11ax)',
      'Speed': '2402Mbps (6GHz) + 2402Mbps (5GHz) + 574Mbps (2.4GHz)',
      'Bands': 'Tri-band',
      'Coverage': 'Up to 5,500 sq ft (3-pack)',
      'Ports': '2× 2.5G Ethernet per unit',
      'Mesh': 'Intelligent mesh, auto-roaming',
      'Features': 'Parental controls, VPN, Alexa',
      'Processors': 'Triple-core 1.5GHz CPU',
    }),
    stock: 22,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['RT-1001', 'RT-1002']),
    active: true,
    featured: false,
    weight: '385g',
    genuine: true,
    tags: JSON.stringify(['router', 'mesh', 'wifi6e', 'tplink', 'networking']),
  },
  {
    name: 'Starlink Standard Kit',
    category: 'Routers',
    subcategory: 'Satellite Internet',
    brand: 'Starlink',
    sku: 'STARLINK-STD',
    description: 'SpaceX Starlink Standard Kit for high-speed satellite internet anywhere in Rwanda and Africa. 100–200 Mbps download, low latency, self-orienting dish, includes router and mounting hardware.',
    price: 59999,
    comparePrice: null,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1606229365485-93a3b8ee0385?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524139094135-77b60a43dc2a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593640408182-31c228f42a89?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White']),
    colorStock: JSON.stringify({ White: 6 }),
    storageOptions: JSON.stringify(['Standard Kit']),
    storageStock: JSON.stringify({ 'Standard Kit': 6 }),
    warrantyOptions: JSON.stringify(['1 Year Starlink']),
    specs: JSON.stringify({
      'Type': 'Low-Earth Orbit Satellite',
      'Download': '100–200 Mbps typical',
      'Upload': '10–20 Mbps typical',
      'Latency': '25–60ms',
      'Dish': 'Self-orienting (no aiming needed)',
      'Setup': 'Plug in + download app — live in minutes',
      'Coverage': 'Kigali + all Rwanda + global roaming',
      'Power': '50W–75W average',
    }),
    stock: 6,
    lowStockThreshold: 2,
    serialNumbers: JSON.stringify(['SL-1001', 'SL-1002']),
    active: true,
    featured: true,
    weight: '1.5kg (kit)',
    genuine: true,
    tags: JSON.stringify(['router', 'starlink', 'satellite', 'internet', 'spacex', 'rural']),
  },

  // ===== Flash Disks =====
  {
    name: 'Samsung FIT Plus USB 3.1 Flash Drive',
    category: 'Storage',
    subcategory: 'Flash Disks',
    brand: 'Samsung',
    sku: 'SAM-FITPLUS',
    description: 'Ultra-compact Samsung FIT Plus USB 3.1 Gen 1 flash drive. Up to 400 MB/s read speeds, metal casing, and a virtually flush profile when plugged in. Perfect for laptops and car media.',
    price: 1999,
    comparePrice: 2499,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593640408182-31c228f42a89?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Metal Gray']),
    colorStock: JSON.stringify({ 'Metal Gray': 50 }),
    storageOptions: JSON.stringify(['32GB', '64GB', '128GB', '256GB']),
    storageStock: JSON.stringify({ '32GB': 20, '64GB': 15, '128GB': 12, '256GB': 3 }),
    warrantyOptions: JSON.stringify(['3 Months', '1 Year Samsung']),
    specs: JSON.stringify({
      'Interface': 'USB 3.1 Gen 1 (backward compat 3.0/2.0)',
      'Read Speed': 'Up to 400 MB/s',
      'Write Speed': 'Up to 110 MB/s',
      'Form Factor': 'Ultra-compact (20.7 × 8.9 × 6.3mm)',
      'Build': 'Metal casing',
      'OS': 'Windows 7+, macOS 10.6+, Linux',
      'Temperature': '-25°C to 85°C',
      'Weight': '3.1g',
    }),
    stock: 50,
    lowStockThreshold: 10,
    serialNumbers: JSON.stringify(['FD-1001', 'FD-1002', 'FD-1003']),
    active: true,
    featured: false,
    weight: '3.1g',
    genuine: true,
    tags: JSON.stringify(['flash-disk', 'usb', 'samsung', 'storage', 'portable']),
  },
  {
    name: 'SanDisk Extreme Pro USB-C Flash Drive',
    category: 'Storage',
    subcategory: 'Flash Disks',
    brand: 'SanDisk',
    sku: 'SANDISK-EXTPRO-C',
    description: 'SanDisk Extreme Pro USB-C (USB 3.2 Gen 2) flash drive with 420 MB/s read, 380 MB/s write. Dual connector (USB-C + USB-A adapter). Metal casing with password protection.',
    price: 2999,
    comparePrice: 3999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1588392382834-a891154bca4d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560732488-6b0df240254a?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Silver']),
    colorStock: JSON.stringify({ Silver: 40 }),
    storageOptions: JSON.stringify(['64GB', '128GB', '256GB', '512GB']),
    storageStock: JSON.stringify({ '64GB': 15, '128GB': 12, '256GB': 8, '512GB': 5 }),
    warrantyOptions: JSON.stringify(['3 Months', '1 Year SanDisk']),
    specs: JSON.stringify({
      'Interface': 'USB 3.2 Gen 2 (USB-C)',
      'Read Speed': '420 MB/s',
      'Write Speed': '380 MB/s',
      'Connector': 'USB-C + USB-A adapter',
      'Security': '128-bit AES password protection',
      'Build': 'Forged metal casing',
      'Temperature': '-25°C to 85°C',
      'Weight': '8g',
    }),
    stock: 40,
    lowStockThreshold: 10,
    serialNumbers: JSON.stringify(['FD-2001', 'FD-2002', 'FD-2003']),
    active: true,
    featured: false,
    weight: '8g',
    genuine: true,
    tags: JSON.stringify(['flash-disk', 'usb-c', 'sandisk', 'storage', 'fast']),
  },

  // ===== Memory Cards =====
  {
    name: 'SanDisk Extreme Pro microSDXC',
    category: 'Storage',
    subcategory: 'Memory Cards',
    brand: 'SanDisk',
    sku: 'SANDISK-MSDXC-PRO',
    description: 'SanDisk Extreme Pro microSD for 4K action cameras and drones. 200 MB/s read, 140 MB/s write, A2 rated for fast app performance. Rated for extreme heat, cold, shocks, and altitude.',
    price: 1499,
    comparePrice: 1999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1560732488-6b0df240254a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1588392382834-a891154bca4d?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Gold/Red']),
    colorStock: JSON.stringify({ 'Gold/Red': 80 }),
    storageOptions: JSON.stringify(['64GB', '128GB', '256GB', '512GB', '1TB']),
    storageStock: JSON.stringify({ '64GB': 25, '128GB': 20, '256GB': 15, '512GB': 10, '1TB': 10 }),
    warrantyOptions: JSON.stringify(['3 Months', '1 Year SanDisk']),
    specs: JSON.stringify({
      'Type': 'microSDXC UHS-I',
      'Read Speed': 'Up to 200 MB/s',
      'Write Speed': 'Up to 140 MB/s',
      'Class': 'UHS Speed Class 3 (U3), V30, A2',
      'Video': '4K UHD, Full HD',
      'Durability': 'Waterproof, shockproof, X-ray proof, temperature-proof',
      'Included': 'SD adapter',
      'Weight': '0.4g',
    }),
    stock: 80,
    lowStockThreshold: 15,
    serialNumbers: JSON.stringify(['MC-1001', 'MC-1002', 'MC-1003', 'MC-1004']),
    active: true,
    featured: false,
    weight: '0.4g',
    genuine: true,
    tags: JSON.stringify(['memory-card', 'microsd', 'sandisk', 'storage', '4k', 'gopro']),
  },
  {
    name: 'Samsung PRO Plus microSDXC 256GB',
    category: 'Storage',
    subcategory: 'Memory Cards',
    brand: 'Samsung',
    sku: 'SAM-PROPLUS-256',
    description: 'Samsung PRO Plus microSD with 180 MB/s read and 130 MB/s write speeds. Built for smartphones, tablets, and cameras. Grade 3 (U3) and V30 video rating. Includes SD adapter.',
    price: 2499,
    comparePrice: 2999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Blue']),
    colorStock: JSON.stringify({ Blue: 60 }),
    storageOptions: JSON.stringify(['128GB', '256GB', '512GB']),
    storageStock: JSON.stringify({ '128GB': 25, '256GB': 20, '512GB': 15 }),
    warrantyOptions: JSON.stringify(['3 Months', '1 Year Samsung']),
    specs: JSON.stringify({
      'Type': 'microSDXC UHS-I',
      'Read Speed': 'Up to 180 MB/s',
      'Write Speed': 'Up to 130 MB/s',
      'Class': 'UHS Speed Class 3 (U3), V30, A2',
      'Video': '4K UHD capable',
      'Durability': 'Waterproof, temperature-proof, X-ray safe, magnetic-safe',
      'Included': 'SD adapter',
      'Weight': '0.35g',
    }),
    stock: 60,
    lowStockThreshold: 12,
    serialNumbers: JSON.stringify(['MC-2001', 'MC-2002', 'MC-2003']),
    active: true,
    featured: false,
    weight: '0.35g',
    genuine: true,
    tags: JSON.stringify(['memory-card', 'microsd', 'samsung', 'storage', '4k']),
  },
  {
    name: 'Sony WH-1000XM6 Headphones',
    category: 'Headphones',
    brand: 'Sony',
    sku: 'SONY-WH1000XM6',
    description: 'Sony WH-1000XM6 with next-gen adaptive noise canceling (16 microphones), 40-hour battery, Auto NC Optimizer, Speak-to-Chat 2.0, and Hi-Res Audio. The definitive noise-canceling headphone.',
    price: 39999,
    comparePrice: 44999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Black', 'Platinum Silver', 'Midnight Blue']),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['1 Year', '2 Years', '3 Years']),
    specs: JSON.stringify({
      'Driver': '40mm custom',
      'Frequency': '4 Hz–40,000 Hz',
      'Battery': '40 hours (ANC on)',
      'Charge Time': '3 hours (10 min = 5 hrs)',
      'Weight': '252g',
      'Connectivity': 'Bluetooth 5.3, multipoint × 2',
      'Microphones': '16 (ANC + call quality)',
      'Noise Canceling': 'Next-gen Adaptive ANC',
    }),
    stock: 25,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['H-6001', 'H-6002', 'H-6003']),
    active: true,
    featured: true,
    weight: '252g',
    tags: JSON.stringify(['headphones', 'noise-canceling', 'sony', 'wireless', 'xm6', 'deal']),
  },

  // ===== Gaming =====
  {
    name: 'PlayStation 5 Slim',
    category: 'Gaming',
    brand: 'Sony',
    sku: 'SONY-PS5-SLIM',
    description: 'Sony PlayStation 5 Slim — 50% smaller than the original PS5, same ultra-high-speed SSD, 4K gaming at 120fps, ray tracing, haptic feedback DualSense controller, and backwards compatible with PS4 games.',
    price: 44999,
    comparePrice: 49999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1486401899868-0e435ed85128?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White', 'Black']),
    storageOptions: JSON.stringify(['1TB (Disc)', '1TB (Digital)']),
    warrantyOptions: JSON.stringify(['1 Year Sony', '2 Years Extended']),
    specs: JSON.stringify({
      'CPU': 'AMD Zen 2 — 8 cores 3.5GHz',
      'GPU': 'AMD RDNA 2 — 10.28 TFLOPS',
      'RAM': '16GB GDDR6',
      'Storage': '1TB Custom NVMe SSD',
      'Resolution': 'Up to 8K (4K 120fps)',
      'Ray Tracing': 'Yes — hardware accelerated',
      'Backwards Compat.': 'PS4 & PS4 Pro games',
      'Audio': 'Tempest 3D AudioTech',
    }),
    stock: 15,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['PS5-1001', 'PS5-1002']),
    active: true,
    featured: true,
    weight: '2.6kg',
    tags: JSON.stringify(['gaming', 'console', 'playstation', 'ps5', 'sony', '4k']),
  },
  {
    name: 'Xbox Series X',
    category: 'Gaming',
    brand: 'Microsoft',
    sku: 'XBOX-SX',
    description: 'Microsoft Xbox Series X — the most powerful Xbox ever with 12 teraflops of GPU performance, 4K 120fps gaming, Quick Resume, Xbox Game Pass Ultimate compatibility, and 1TB SSD.',
    price: 49999,
    comparePrice: 54999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Carbon Black']),
    storageOptions: JSON.stringify(['1TB SSD']),
    warrantyOptions: JSON.stringify(['1 Year Microsoft', '2 Years Extended']),
    specs: JSON.stringify({
      'CPU': 'AMD Zen 2 — 8 cores 3.8GHz',
      'GPU': 'AMD RDNA 2 — 12 TFLOPS',
      'RAM': '16GB GDDR6',
      'Storage': '1TB NVMe SSD',
      'Resolution': '4K 120fps / 8K',
      'Quick Resume': 'Yes — multiple games',
      'Game Pass': 'Compatible with Ultimate',
      'Backwards Compat.': 'Thousands of Xbox/360/One titles',
    }),
    stock: 12,
    lowStockThreshold: 3,
    serialNumbers: JSON.stringify(['XBX-1001', 'XBX-1002']),
    active: true,
    featured: true,
    weight: '4.45kg',
    tags: JSON.stringify(['gaming', 'console', 'xbox', 'microsoft', '4k', 'game-pass']),
  },
  {
    name: 'Nintendo Switch OLED',
    category: 'Gaming',
    brand: 'Nintendo',
    sku: 'NINTENDO-SW-OLED',
    description: 'Nintendo Switch OLED with 7-inch vibrant OLED screen, enhanced audio, wide adjustable stand, 64GB internal storage, and LAN port in dock. Play at home or on the go with beloved Nintendo titles.',
    price: 34999,
    comparePrice: 37999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1600861194942-f883de0dfe96?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White', 'Neon Blue/Red']),
    storageOptions: JSON.stringify(['64GB (expandable MicroSD)']),
    warrantyOptions: JSON.stringify(['1 Year Nintendo', '2 Years Extended']),
    specs: JSON.stringify({
      'Screen': '7" OLED 720p (handheld)',
      'TV Output': '1080p',
      'Battery': '4.5–9 hours',
      'Storage': '64GB + MicroSD expandable',
      'Connectivity': 'Wi-Fi, Bluetooth 4.1, LAN (dock)',
      'Controllers': 'Joy-Con with HD Rumble',
      'Stand': 'Wide adjustable kickstand',
      'Weight': '320g (with Joy-Con)',
    }),
    stock: 20,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['NSW-1001', 'NSW-1002', 'NSW-1003']),
    active: true,
    featured: true,
    weight: '320g',
    tags: JSON.stringify(['gaming', 'console', 'nintendo', 'switch', 'portable', 'oled']),
  },
  {
    name: 'Sony DualSense Edge Controller',
    category: 'Gaming',
    brand: 'Sony',
    sku: 'SONY-DUALSENSE-EDGE',
    description: 'Sony DualSense Edge wireless controller for PS5 — customizable back buttons, swappable stick caps, adjustable trigger depth, remappable controls, and carrying case. The ultimate pro PS5 controller.',
    price: 19999,
    comparePrice: 22999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1486401899868-0e435ed85128?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White']),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['1 Year Sony', '2 Years Extended']),
    specs: JSON.stringify({
      'Compatibility': 'PS5, PC (USB & Bluetooth)',
      'Back Buttons': '2 swappable — half-dome or lever',
      'Trigger Depth': 'Adjustable (full / mid / short)',
      'Stick Caps': 'High & low interchangeable',
      'Haptic Feedback': 'Yes — advanced',
      'Adaptive Triggers': 'Yes — customizable tension',
      'Battery': '12h (vs 12h standard)',
      'USB': 'USB-C braided cable included',
    }),
    stock: 18,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['DSE-1001', 'DSE-1002']),
    active: true,
    featured: false,
    weight: '325g',
    tags: JSON.stringify(['gaming', 'controller', 'ps5', 'sony', 'pro', 'dualsense']),
  },

  // ── Smart Home ──────────────────────────────────────────────────────────────
  {
    name: 'Amazon Echo Show 10 (3rd Gen)',
    category: 'Smart Home',
    brand: 'Amazon',
    sku: 'AMZ-ECHOSHOW10-3G',
    description: "Echo Show 10 with a 10.1\" HD display that automatically rotates to face you. Built-in smart home hub, Zigbee, Thread & Sidewalk support, 13MP camera, and rich stereo sound.",
    price: 24999,
    comparePrice: 29999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512446816042-444d641267d4?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Charcoal', 'Glacier White']),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['1 Year Amazon', '2 Years Extended']),
    specs: JSON.stringify({
      'Display': '10.1" HD (1280×800)',
      'Rotation': 'Auto-rotating motor',
      'Camera': '13MP auto-framing',
      'Audio': 'Directional 2.1 stereo + woofer',
      'Smart Hub': 'Zigbee, Thread, Sidewalk',
      'Connectivity': 'Wi-Fi 6, Bluetooth 5.0',
      'Privacy': 'Physical camera shutter + mic off button',
      'Power': 'AC adapter (included)',
    }),
    stock: 22,
    lowStockThreshold: 5,
    serialNumbers: JSON.stringify(['ESH-3001', 'ESH-3002', 'ESH-3003']),
    active: true,
    featured: true,
    weight: '2.55kg',
    tags: JSON.stringify(['smart home', 'echo', 'alexa', 'amazon', 'display', 'hub']),
  },
  {
    name: 'Google Nest Hub Max',
    category: 'Smart Home',
    brand: 'Google',
    sku: 'GOOGLE-NESTHUBMAX',
    description: 'Google Nest Hub Max with a 10" HD display, Google Assistant, built-in Nest Cam for home monitoring, and crisp full-range speaker. Control your smart home hands-free.',
    price: 21999,
    comparePrice: 25999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['Chalk', 'Charcoal']),
    storageOptions: JSON.stringify(['Standard']),
    warrantyOptions: JSON.stringify(['1 Year Google', '2 Years Extended']),
    specs: JSON.stringify({
      'Display': '10" HD LCD (1280×800)',
      'Camera': '6.5MP Nest Cam with face recognition',
      'Speaker': 'Full-range + woofer stereo',
      'Assistant': 'Google Assistant',
      'Smart Hub': 'Works with Matter, Zigbee (via Google)',
      'Connectivity': 'Wi-Fi, Bluetooth',
      'Sensors': 'Ambient light, ultrasonic presence',
      'Privacy': 'Camera & mic off switch',
    }),
    stock: 15,
    lowStockThreshold: 4,
    serialNumbers: JSON.stringify(['NHM-2001', 'NHM-2002']),
    active: true,
    featured: false,
    weight: '1.7kg',
    tags: JSON.stringify(['smart home', 'google', 'nest', 'assistant', 'hub', 'display']),
  },
  {
    name: 'Philips Hue Starter Kit (4 Bulbs + Bridge)',
    category: 'Smart Home',
    brand: 'Philips',
    sku: 'PHILIPS-HUE-4BULB-KIT',
    description: 'Philips Hue White & Colour Ambiance starter kit — 4× A19 smart bulbs (16 million colours, 800 lm each) + Hue Bridge. Works with Alexa, Google, HomeKit, and Matter.',
    price: 18999,
    comparePrice: 22999,
    images: JSON.stringify([
      'https://images.unsplash.com/photo-1563461661026-49631dd5d68e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ]),
    colors: JSON.stringify(['White (kit)']),
    storageOptions: JSON.stringify(['4-Bulb Kit', '6-Bulb Kit']),
    warrantyOptions: JSON.stringify(['2 Years Philips', '3 Years Extended']),
    specs: JSON.stringify({
      'Bulb Type': 'A19 E26/E27',
      'Brightness': '800 lm per bulb',
      'Colours': '16 million (RGB + warm white)',
      'Protocol': 'Zigbee via Hue Bridge',
      'Compatibility': 'Alexa, Google Assistant, Apple HomeKit, Matter',
      'App': 'Philips Hue app (iOS/Android)',
      'Lifespan': '25,000 hours',
      'Power': '9W per bulb (≈60W equivalent)',
    }),
    stock: 30,
    lowStockThreshold: 6,
    serialNumbers: JSON.stringify(['PHK-5001', 'PHK-5002', 'PHK-5003']),
    active: true,
    featured: true,
    weight: '800g',
    tags: JSON.stringify(['smart home', 'philips', 'hue', 'bulb', 'lighting', 'matter']),
  },
];

async function main() {
  // Delete related records first to avoid foreign key errors
  await prisma.notification.deleteMany();
  await prisma.review.deleteMany().catch(() => {});
  await prisma.repairTicket.deleteMany().catch(() => {});
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.tradeIn.deleteMany().catch(() => {});
  await prisma.marketplaceListing.deleteMany().catch(() => {});
  await prisma.product.deleteMany();

  for (const product of products) {
    await prisma.product.create({ data: product });
  }
  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
